package com.bwie.wangyanmin20200106.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bwie.wangyanmin20200106.model.dao.ClassflyDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CLASSFLY_DAO".
*/
public class ClassflyDaoDao extends AbstractDao<ClassflyDao, Void> {

    public static final String TABLENAME = "CLASSFLY_DAO";

    /**
     * Properties of entity ClassflyDao.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ClassflyDao = new Property(0, String.class, "classflyDao", false, "CLASSFLY_DAO");
    }


    public ClassflyDaoDao(DaoConfig config) {
        super(config);
    }
    
    public ClassflyDaoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CLASSFLY_DAO\" (" + //
                "\"CLASSFLY_DAO\" TEXT);"); // 0: classflyDao
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CLASSFLY_DAO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ClassflyDao entity) {
        stmt.clearBindings();
 
        String classflyDao = entity.getClassflyDao();
        if (classflyDao != null) {
            stmt.bindString(1, classflyDao);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ClassflyDao entity) {
        stmt.clearBindings();
 
        String classflyDao = entity.getClassflyDao();
        if (classflyDao != null) {
            stmt.bindString(1, classflyDao);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public ClassflyDao readEntity(Cursor cursor, int offset) {
        ClassflyDao entity = new ClassflyDao( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // classflyDao
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ClassflyDao entity, int offset) {
        entity.setClassflyDao(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(ClassflyDao entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(ClassflyDao entity) {
        return null;
    }

    @Override
    public boolean hasKey(ClassflyDao entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
